const domainMap: Record<string, string> = {
  netflix: "netflix.com",
  hotstar: "hotstar.com",
  "prime-video": "primevideo.com",
  jiocinema: "jiocinema.com",
  sonyliv: "sonyliv.com",
  zee5: "zee5.com",
  "youtube-premium": "youtube.com",
  "apple-tv": "tv.apple.com",
  spotify: "spotify.com",
  "apple-music": "music.apple.com",
  jiosaavn: "jiosaavn.com",
  gaana: "gaana.com",
  "youtube-music": "music.youtube.com",
  "xbox-gamepass": "xbox.com",
  "ps-plus": "playstation.com",
  notion: "notion.so",
  "chatgpt-plus": "openai.com",
  "microsoft-365": "microsoft.com",
  icloud: "icloud.com",
  "google-one": "one.google.com",
  dropbox: "dropbox.com",
  "et-prime": "economictimes.com",
  "the-hindu": "thehindu.com",
  cultfit: "cult.fit",
  "jio-fiber": "jio.com",
  "airtel-xstream": "airtel.in",
  "act-fibernet": "actcorp.in",
  "bsnl-fiber": "bsnl.co.in",
  "jio-mobile": "jio.com",
  "airtel-mobile": "airtel.in",
  "vi-mobile": "myvi.in",
  "bsnl-mobile": "bsnl.co.in",
  bescom: "bescom.karnataka.gov.in",
  "tata-power": "tatapower.com",
  "hdfc-cc": "hdfcbank.com",
  "icici-cc": "icicibank.com",
  "sbi-cc": "sbicard.com",
  "amex-india": "americanexpress.com",
  "cultfit-gym": "cult.fit",
  "golds-gym": "goldsgym.com",
  "star-health": "starhealth.in",
  "hdfc-ergo": "hdfcergo.com",
  "digit-insurance": "godigit.com",
  "planet-fitness": "planetfitness.com",
};

export function getLogoUrl(id: string): string {
  const domain = domainMap[id];
  if (!domain) return "";
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}
